# Generated by Django 4.1.4 on 2023-02-21 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TableMangement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="reservations",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="TableMangement.reservation",
            ),
        ),
    ]
