# Generated by Django 4.1.4 on 2023-02-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TableMangement", "0003_remove_table_reservations_reservation_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="table_number",
            field=models.IntegerField(unique=True),
        ),
    ]
