# Generated by Django 4.1.4 on 2023-02-21 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TableMangement", "0002_alter_table_reservations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="reservations",
        ),
        migrations.AddField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="TableMangement.table",
            ),
        ),
    ]
